version: '3.5'

services:
      
  db:
    image: mysql:latest
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    env_file: .env
    environment:
      - MYSQL_DATABASE=main
    volumes:
      - ./db-data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - dp_main

  wordpress:
    depends_on:
      - db
    image: wordpress:5.3.2-fpm-alpine
    container_name: wordpress
    restart: always
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=main
    volumes:
      - ./wordpress:/var/www/html
      - ./php-conf/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - dp_main

  webserver:
    depends_on:
      - wordpress
    image: nginx:latest
    container_name: webserver
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks: 
      - dp_main

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8000:80
    links:
      - db
    environment:
      PMA_HOST: mysql

       
volumes:
  wordpress:
  db-data:

networks:
  dp_main:
    driver: bridge